spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  dblocal:
    datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      username: system
      password: 123456
  dbanalise:
    datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@dbanalise.cn1v5eurmtkf.sa-east-1.rds.amazonaws.com:1521:XE
      username: jivacloud
      password: J1v4#Cl0ud
  dbjivacloudse:
    datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@dbjivacloudse.cn1v5eurmtkf.sa-east-1.rds.amazonaws.com:1521:XE
      username: jivacloud
      password: J1v4#Cl0ud
  dbjivacloudse2:
    datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@dbjivacloudse2.cn1v5eurmtkf.sa-east-1.rds.amazonaws.com:1521:ORCL
      username: jivacloud
      password: J1v4#Cl0ud
  dbteste:
    datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@ec2-54-227-198-142.compute-1.amazonaws.com:1521:ORCL
      username: system
      password: J1v4#Cl0ud
